// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  guideSidebar: [{ type: 'autogenerated', dirName: 'guide' }],
  contributorsSidebar: [
    'contributors/get-started',
    'contributors/principles',
    'contributors/logging',
    'contributors/errors',
    'contributors/eslint-rules',
  ],
}

module.exports = sidebars
