#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

pushd $SCRIPT_DIR/.. > /dev/null
pnpm build:affected
popd > /dev/null

$SCRIPT_DIR/../packages/gestaltjs/bin/dev.js $@
